import { Product } from '@/types/products';
import { CustomerOrganization, UserProfile } from '@/types/customer';
import { Lead } from '@/types/crm';
import { Order, Invoice } from '@/types/orders';

export const INITIAL_PRODUCTS: Product[] = [
  // Fresh Produce - Vegetables & Salad
  {
    id: 'prod-001',
    sku: 'FP-TOM-01',
    name: 'San Marzano Vine Tomatoes',
    category: 'fresh_produce',
    subcategory: 'vegetables',
    categoryLabel: 'Fresh Produce',
    description: 'Sweet, intense flavour with tender flesh. Perfect for sauces, salads, and garnishes.',
    packSize: '6kg Box',
    unit: 'box',
    basePrice: 9.80,
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Campania, Italy',
    inStock: true,
    featured: true,
  },
  {
    id: 'prod-002',
    sku: 'FP-AVO-02',
    name: 'Ready-to-Eat Hass Avocados (Size 16)',
    category: 'fresh_produce',
    subcategory: 'fruit',
    categoryLabel: 'Fresh Produce',
    description: 'Perfect ripeness guaranteed. Creamy texture, ideal for brunch services and purées.',
    packSize: '16 Count Box',
    unit: 'box',
    basePrice: 18.50,
    imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Michoacán, Mexico',
    inStock: true,
    featured: true,
  },
  {
    id: 'prod-003',
    sku: 'FP-SPI-03',
    name: 'Washed Baby Spinach Leaves',
    category: 'fresh_produce',
    subcategory: 'salad',
    categoryLabel: 'Fresh Produce',
    description: 'Triple-washed young tender spinach leaves. Ready for service, zero prep required.',
    packSize: '1kg Bag',
    unit: 'bag',
    basePrice: 4.90,
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&auto=format&fit=crop&q=80',
    moq: 2,
    origin: 'Evesham, Worcestershire, UK',
    inStock: true,
  },
  {
    id: 'prod-004',
    sku: 'FP-MUSH-04',
    name: 'Chef’s Wild Forest Mushroom Mix',
    category: 'fresh_produce',
    subcategory: 'vegetables',
    categoryLabel: 'Fresh Produce',
    description: 'Seasonal selection of Girolles, Pied de Mouton, Trompettes, and King Oyster mushrooms.',
    packSize: '1kg Basket',
    unit: 'kg',
    basePrice: 22.00,
    imageUrl: 'https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Dordogne, France',
    inStock: true,
    featured: true,
  },
  {
    id: 'prod-005',
    sku: 'FP-LEM-05',
    name: 'Amalfi Coast PGI Lemons (Unwaxed)',
    category: 'fresh_produce',
    subcategory: 'citrus',
    categoryLabel: 'Fresh Produce',
    description: 'Aromatic, intensely fragrant untreated rind and sweet juice. Prized for cocktails and seafood.',
    packSize: '5kg Crate',
    unit: 'crate',
    basePrice: 16.50,
    imageUrl: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Sorrento, Italy',
    inStock: true,
  },
  {
    id: 'prod-006',
    sku: 'FP-POT-06',
    name: 'Selected Maris Piper Washed Potatoes',
    category: 'fresh_produce',
    subcategory: 'potatoes_onions',
    categoryLabel: 'Fresh Produce',
    description: 'Consistent dry matter for perfect hand-cut chips, mash, and golden roast potatoes.',
    packSize: '25kg Sack',
    unit: 'sack',
    basePrice: 14.20,
    imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&auto=format&fit=crop&q=80',
    moq: 2,
    origin: 'Lincolnshire, UK',
    inStock: true,
  },
  {
    id: 'prod-007',
    sku: 'FP-HERB-07',
    name: 'Live Micro Coriander & Pea Shoots Punnet Mix',
    category: 'fresh_produce',
    subcategory: 'herbs',
    categoryLabel: 'Fresh Produce',
    description: 'Living microgreens with root sponge. Exceptional shelf-life and vibrant chef garnish.',
    packSize: '8 Punnet Case',
    unit: 'case',
    basePrice: 12.80,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Warwickshire, UK',
    inStock: true,
  },

  // Foodservice - Dairy, Meats & Dry Goods
  {
    id: 'prod-008',
    sku: 'FS-CRM-08',
    name: 'Cotswold Dairy Pasteurized Double Cream',
    category: 'dairy_eggs',
    subcategory: 'dairy',
    categoryLabel: 'Dairy & Eggs',
    description: '48% butterfat content from grass-fed West Country cows. Whips beautifully without splitting.',
    packSize: '2 Litre Bottle',
    unit: 'bottle',
    basePrice: 7.90,
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
    moq: 2,
    origin: 'Gloucestershire, UK',
    allergens: ['Milk'],
    inStock: true,
  },
  {
    id: 'prod-009',
    sku: 'FS-EGG-09',
    name: 'British Lion Free Range Large Eggs',
    category: 'dairy_eggs',
    subcategory: 'eggs',
    categoryLabel: 'Dairy & Eggs',
    description: 'Class A large eggs with rich golden yolks. Graded and packed within 24 hours of lay.',
    packSize: '15 Dozen (180 Eggs)',
    unit: 'outer',
    basePrice: 34.50,
    imageUrl: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Staffordshire, UK',
    allergens: ['Eggs'],
    inStock: true,
    featured: true,
  },
  {
    id: 'prod-010',
    sku: 'FS-BEEF-10',
    name: '28-Day Dry-Aged British Ribeye Steaks (250g)',
    category: 'meat_poultry',
    subcategory: 'beef_lamb',
    categoryLabel: 'Meat & Poultry',
    description: 'Himalayan salt chamber aged prime Hereford beef. Exceptional marbling and depth of flavour.',
    packSize: 'Pack of 10 (2.5kg)',
    unit: 'pack',
    basePrice: 78.00,
    imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Herefordshire, UK',
    inStock: true,
    featured: true,
  },
  {
    id: 'prod-011',
    sku: 'FS-TRUF-11',
    name: 'Italian White Truffle Infused EVOO',
    category: 'specialty',
    subcategory: 'truffles_caviar',
    categoryLabel: 'Specialty & Delicatessen',
    description: 'Cold-pressed extra virgin olive oil infused with real Tuber Magnatum Pico white truffle aroma.',
    packSize: '500ml Glass Bottle',
    unit: 'bottle',
    basePrice: 19.50,
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Piedmont, Italy',
    inStock: true,
  },
  {
    id: 'prod-012',
    sku: 'FS-CHOC-12',
    name: 'Valrhona Guanaja 70% Dark Chocolate Feves',
    category: 'dry_goods',
    subcategory: 'chocolate_pastry',
    categoryLabel: 'Pastry & Dry Goods',
    description: 'Iconic Grand Cru blend of Criollo and Trinitario beans. Benchmark pastry chocolate.',
    packSize: '3kg Bag',
    unit: 'bag',
    basePrice: 42.00,
    imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Tain-l’Hermitage, France',
    allergens: ['Soybeans', 'May contain Milk/Nuts'],
    inStock: true,
  },
];

export const INITIAL_ORGANIZATIONS: CustomerOrganization[] = [
  {
    id: 'org-rootwills-partner',
    name: 'Rootwills Commercial Partner',
    companyRegNumber: '14892019',
    vatNumber: 'GB 928 4810 22',
    sector: 'fine_dining',
    creditTier: 'premium',
    creditLimit: 15000,
    creditUsed: 0,
    paymentTerms: '30 Days Net',
    assignedSalesRep: 'Marcus Vance (Commercial Sales Desk)',
    assignedDepot: 'Birmingham Central Hub (B5 5JR)',
    discountTierPercent: 5.0,
    priceOverrides: {},
    lastOrderDate: undefined,
    status: 'active',
    locations: [
      {
        id: 'loc-primary-site',
        name: 'Main Kitchen & Coldroom',
        addressLine1: 'Central Commercial Premises',
        city: 'Birmingham',
        postcode: 'B5 5JR',
        deliveryInstructions: 'Deliver to kitchen inwards door before 07:00 AM.',
        isPrimary: true,
      },
    ],
  },
];

export const INITIAL_LEADS: Lead[] = [];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'order-po-89210',
    orderNumber: 'PO-89210',
    organizationId: 'org-rootwills-partner',
    organizationName: 'Rootwills Commercial Partner',
    locationId: 'loc-primary-site',
    locationName: 'The Grand Hotel Birmingham - Main Kitchen & Coldroom',
    status: 'delivered',
    items: [
      {
        productId: 'prod-001',
        sku: 'FP-TOM-01',
        name: 'San Marzano Vine Tomatoes',
        packSize: '6kg Box',
        qty: 4,
        unitPrice: 9.80,
        totalPrice: 39.20,
      },
      {
        productId: 'prod-002',
        sku: 'FP-AVO-02',
        name: 'Ready-to-Eat Hass Avocados (Size 16)',
        packSize: '16 Count Box',
        qty: 3,
        unitPrice: 18.50,
        totalPrice: 55.50,
      },
      {
        productId: 'prod-004',
        sku: 'FP-MUSH-04',
        name: 'Chef’s Wild Forest Mushroom Mix',
        packSize: '1kg Basket',
        qty: 5,
        unitPrice: 22.00,
        totalPrice: 110.00,
      },
      {
        productId: 'prod-009',
        sku: 'FS-EGG-09',
        name: 'British Lion Free Range Large Eggs',
        packSize: '15 Dozen (180 Eggs)',
        qty: 2,
        unitPrice: 34.50,
        totalPrice: 69.00,
      },
      {
        productId: 'prod-008',
        sku: 'FS-CRM-08',
        name: 'Cotswold Dairy Pasteurized Double Cream',
        packSize: '2 Litre Bottle',
        qty: 6,
        unitPrice: 7.90,
        totalPrice: 47.40,
      },
      {
        productId: 'prod-007',
        sku: 'FP-HERB-07',
        name: 'Live Micro Coriander & Pea Shoots Punnet Mix',
        packSize: '8 Punnet Case',
        qty: 2,
        unitPrice: 12.80,
        totalPrice: 25.60,
      },
      {
        productId: 'prod-006',
        sku: 'FP-POT-06',
        name: 'Selected Maris Piper Washed Potatoes',
        packSize: '25kg Sack',
        qty: 4,
        unitPrice: 14.20,
        totalPrice: 56.80,
      },
    ],
    subtotal: 403.50,
    vatTotal: 9.48,
    total: 412.98,
    isStandingOrder: false,
    deliveryDate: 'Today (Early Drop)',
    deliverySlot: '05:00 - 07:30 AM',
    deliveryNotes: 'Kitchen keyholder entrance on Barwick St. Code #4912. Stack dairy on lower chilled shelf and produce in middle bay.',
    pod: {
      recipientName: 'Chef Marcus Wareing (Head Chef)',
      signatureDataUrl: 'verified_digital_signature_hash',
      vanProbeChilledTemp: '+2.4°C',
      vanProbeFrozenTemp: '-18.5°C',
      deliveredAt: '06:48 AM',
      driverName: 'David Fletcher (Van #04 - Digbeth Hub)',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    trackingHistory: [
      { status: 'received', timestamp: '22:42 GMT', note: 'Order placed by kitchen manager & inventory locked' },
      { status: 'confirmed', timestamp: '23:15 GMT', note: 'Night logistics manager confirmed delivery schedule' },
      { status: 'picking', timestamp: '02:30 GMT', note: 'Picked & quality inspected at Digbeth Central Hub (+2.2°C hold)' },
      { status: 'dispatch_ready', timestamp: '04:15 GMT', note: 'Chilled cargo loaded onto Mercedes Sprinter Van #04' },
      { status: 'out_for_delivery', timestamp: '05:40 GMT', note: 'Van departed Digbeth Hub; GPS telemetry live' },
      { status: 'delivered', timestamp: '06:48 GMT', note: 'Delivered to kitchen coldroom & signed by Chef Marcus Wareing' },
    ],
  },
  {
    id: 'order-po-89214',
    orderNumber: 'PO-89214',
    organizationId: 'org-rootwills-partner',
    organizationName: 'Rootwills Commercial Partner',
    locationId: 'loc-primary-site',
    locationName: 'The Grand Hotel Birmingham - Main Kitchen & Coldroom',
    status: 'out_for_delivery',
    items: [
      {
        productId: 'prod-003',
        sku: 'FP-SPI-03',
        name: 'Washed Baby Spinach Leaves',
        packSize: '1kg Bag',
        qty: 6,
        unitPrice: 4.90,
        totalPrice: 29.40,
      },
      {
        productId: 'prod-010',
        sku: 'FS-BEEF-10',
        name: '28-Day Dry-Aged British Ribeye Steaks (250g)',
        packSize: 'Pack of 10 (2.5kg)',
        qty: 2,
        unitPrice: 78.00,
        totalPrice: 156.00,
      },
      {
        productId: 'prod-012',
        sku: 'FS-CHOC-12',
        name: 'Valrhona Guanaja 70% Dark Chocolate Feves',
        packSize: '3kg Bag',
        qty: 1,
        unitPrice: 42.00,
        totalPrice: 42.00,
      },
    ],
    subtotal: 227.40,
    vatTotal: 8.40,
    total: 235.80,
    isStandingOrder: true,
    recurrence: 'mon_wed_fri',
    deliveryDate: 'Tomorrow Morning',
    deliverySlot: '06:00 - 08:00 AM',
    deliveryNotes: 'Morning service urgent stock.',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    trackingHistory: [
      { status: 'received', timestamp: '21:10 GMT', note: 'Standing order triggered automatically' },
      { status: 'confirmed', timestamp: '22:00 GMT', note: 'Locked contract pricing applied' },
      { status: 'picking', timestamp: '01:45 GMT', note: 'Cold store staging completed' },
      { status: 'dispatch_ready', timestamp: '04:00 GMT', note: 'Dual-temp van manifest locked' },
      { status: 'out_for_delivery', timestamp: '05:15 GMT', note: 'Driver en route (Approx ETA: 06:15 AM)' },
    ],
  },
];

export const INITIAL_INVOICES: Invoice[] = [];
