import { Product } from '@/types/products';
import { CustomerOrganization, UserProfile } from '@/types/customer';
import { Lead } from '@/types/crm';
import { Order, Invoice } from '@/types/orders';

export const INITIAL_PRODUCTS: Product[] = [
  // Fresh Produce - Vegetables & Salad
  {
    id: 'prod-001',
    sku: 'FP-TOM-01',
    name: 'San Marzano Vine Tomatoes',
    category: 'fresh_produce',
    subcategory: 'vegetables',
    categoryLabel: 'Fresh Produce',
    description: 'Sweet, intense flavour with tender flesh. Perfect for sauces, salads, and garnishes.',
    packSize: '6kg Box',
    unit: 'box',
    basePrice: 9.80,
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Campania, Italy',
    inStock: true,
    featured: true,
  },
  {
    id: 'prod-002',
    sku: 'FP-AVO-02',
    name: 'Ready-to-Eat Hass Avocados (Size 16)',
    category: 'fresh_produce',
    subcategory: 'fruit',
    categoryLabel: 'Fresh Produce',
    description: 'Perfect ripeness guaranteed. Creamy texture, ideal for brunch services and purées.',
    packSize: '16 Count Box',
    unit: 'box',
    basePrice: 18.50,
    imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Michoacán, Mexico',
    inStock: true,
    featured: true,
  },
  {
    id: 'prod-003',
    sku: 'FP-SPI-03',
    name: 'Washed Baby Spinach Leaves',
    category: 'fresh_produce',
    subcategory: 'salad',
    categoryLabel: 'Fresh Produce',
    description: 'Triple-washed young tender spinach leaves. Ready for service, zero prep required.',
    packSize: '1kg Bag',
    unit: 'bag',
    basePrice: 4.90,
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&auto=format&fit=crop&q=80',
    moq: 2,
    origin: 'Evesham, Worcestershire, UK',
    inStock: true,
  },
  {
    id: 'prod-004',
    sku: 'FP-MUSH-04',
    name: 'Chef’s Wild Forest Mushroom Mix',
    category: 'fresh_produce',
    subcategory: 'vegetables',
    categoryLabel: 'Fresh Produce',
    description: 'Seasonal selection of Girolles, Pied de Mouton, Trompettes, and King Oyster mushrooms.',
    packSize: '1kg Basket',
    unit: 'kg',
    basePrice: 22.00,
    imageUrl: 'https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Dordogne, France',
    inStock: true,
    featured: true,
  },
  {
    id: 'prod-005',
    sku: 'FP-LEM-05',
    name: 'Amalfi Coast PGI Lemons (Unwaxed)',
    category: 'fresh_produce',
    subcategory: 'citrus',
    categoryLabel: 'Fresh Produce',
    description: 'Aromatic, intensely fragrant untreated rind and sweet juice. Prized for cocktails and seafood.',
    packSize: '5kg Crate',
    unit: 'crate',
    basePrice: 16.50,
    imageUrl: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Sorrento, Italy',
    inStock: true,
  },
  {
    id: 'prod-006',
    sku: 'FP-POT-06',
    name: 'Selected Maris Piper Washed Potatoes',
    category: 'fresh_produce',
    subcategory: 'potatoes_onions',
    categoryLabel: 'Fresh Produce',
    description: 'Consistent dry matter for perfect hand-cut chips, mash, and golden roast potatoes.',
    packSize: '25kg Sack',
    unit: 'sack',
    basePrice: 14.20,
    imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&auto=format&fit=crop&q=80',
    moq: 2,
    origin: 'Lincolnshire, UK',
    inStock: true,
  },
  {
    id: 'prod-007',
    sku: 'FP-HERB-07',
    name: 'Live Micro Coriander & Pea Shoots Punnet Mix',
    category: 'fresh_produce',
    subcategory: 'herbs',
    categoryLabel: 'Fresh Produce',
    description: 'Living microgreens with root sponge. Exceptional shelf-life and vibrant chef garnish.',
    packSize: '8 Punnet Case',
    unit: 'case',
    basePrice: 12.80,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Warwickshire, UK',
    inStock: true,
  },

  // Foodservice - Dairy, Meats & Dry Goods
  {
    id: 'prod-008',
    sku: 'FS-CRM-08',
    name: 'Cotswold Dairy Pasteurized Double Cream',
    category: 'dairy_eggs',
    subcategory: 'dairy',
    categoryLabel: 'Dairy & Eggs',
    description: '48% butterfat content from grass-fed West Country cows. Whips beautifully without splitting.',
    packSize: '2 Litre Bottle',
    unit: 'bottle',
    basePrice: 7.90,
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
    moq: 2,
    origin: 'Gloucestershire, UK',
    allergens: ['Milk'],
    inStock: true,
  },
  {
    id: 'prod-009',
    sku: 'FS-EGG-09',
    name: 'British Lion Free Range Large Eggs',
    category: 'dairy_eggs',
    subcategory: 'eggs',
    categoryLabel: 'Dairy & Eggs',
    description: 'Class A large eggs with rich golden yolks. Graded and packed within 24 hours of lay.',
    packSize: '15 Dozen (180 Eggs)',
    unit: 'outer',
    basePrice: 34.50,
    imageUrl: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Staffordshire, UK',
    allergens: ['Eggs'],
    inStock: true,
    featured: true,
  },
  {
    id: 'prod-010',
    sku: 'FS-BEEF-10',
    name: '28-Day Dry-Aged British Ribeye Steaks (250g)',
    category: 'meat_poultry',
    subcategory: 'beef_lamb',
    categoryLabel: 'Meat & Poultry',
    description: 'Himalayan salt chamber aged prime Hereford beef. Exceptional marbling and depth of flavour.',
    packSize: 'Pack of 10 (2.5kg)',
    unit: 'pack',
    basePrice: 78.00,
    imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Herefordshire, UK',
    inStock: true,
    featured: true,
  },
  {
    id: 'prod-011',
    sku: 'FS-TRUF-11',
    name: 'Italian White Truffle Infused EVOO',
    category: 'specialty',
    subcategory: 'truffles_caviar',
    categoryLabel: 'Specialty & Delicatessen',
    description: 'Cold-pressed extra virgin olive oil infused with real Tuber Magnatum Pico white truffle aroma.',
    packSize: '500ml Glass Bottle',
    unit: 'bottle',
    basePrice: 19.50,
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Piedmont, Italy',
    inStock: true,
  },
  {
    id: 'prod-012',
    sku: 'FS-CHOC-12',
    name: 'Valrhona Guanaja 70% Dark Chocolate Feves',
    category: 'dry_goods',
    subcategory: 'chocolate_pastry',
    categoryLabel: 'Pastry & Dry Goods',
    description: 'Iconic Grand Cru blend of Criollo and Trinitario beans. Benchmark pastry chocolate.',
    packSize: '3kg Bag',
    unit: 'bag',
    basePrice: 42.00,
    imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Tain-l’Hermitage, France',
    allergens: ['Soybeans', 'May contain Milk/Nuts'],
    inStock: true,
  },
];

export const INITIAL_ORGANIZATIONS: CustomerOrganization[] = [
  {
    id: 'org-rootwills-partner',
    name: 'Rootwills Commercial Partner',
    companyRegNumber: '14892019',
    vatNumber: 'GB 928 4810 22',
    sector: 'fine_dining',
    creditTier: 'premium',
    creditLimit: 15000,
    creditUsed: 0,
    paymentTerms: '30 Days Net',
    assignedSalesRep: 'Marcus Vance (Commercial Sales Desk)',
    assignedDepot: 'Birmingham Central Hub (B5 5JR)',
    discountTierPercent: 5.0,
    priceOverrides: {},
    lastOrderDate: undefined,
    status: 'active',
    locations: [
      {
        id: 'loc-primary-site',
        name: 'Main Kitchen & Coldroom',
        addressLine1: 'Central Commercial Premises',
        city: 'Birmingham',
        postcode: 'B5 5JR',
        deliveryInstructions: 'Deliver to kitchen inwards door before 07:00 AM.',
        isPrimary: true,
      },
    ],
  },
];

export const INITIAL_LEADS: Lead[] = [];

export const INITIAL_ORDERS: Order[] = [];

export const INITIAL_INVOICES: Invoice[] = [];
