import { Product } from '@/types/products';
import { CustomerOrganization, UserProfile } from '@/types/customer';
import { Lead } from '@/types/crm';
import { Order, Invoice } from '@/types/orders';

export const INITIAL_PRODUCTS: Product[] = [
  // Fresh Produce - Vegetables & Salad
  {
    id: 'prod-001',
    sku: 'FP-TOM-01',
    name: 'San Marzano Vine Tomatoes',
    category: 'fresh_produce',
    subcategory: 'vegetables',
    categoryLabel: 'Fresh Produce',
    description: 'Sweet, intense flavour with tender flesh. Perfect for sauces, salads, and garnishes.',
    packSize: '6kg Box',
    unit: 'box',
    basePrice: 9.80,
    imageUrl: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Campania, Italy',
    inStock: true,
    featured: true,
  },
  {
    id: 'prod-002',
    sku: 'FP-AVO-02',
    name: 'Ready-to-Eat Hass Avocados (Size 16)',
    category: 'fresh_produce',
    subcategory: 'fruit',
    categoryLabel: 'Fresh Produce',
    description: 'Perfect ripeness guaranteed. Creamy texture, ideal for brunch services and purées.',
    packSize: '16 Count Box',
    unit: 'box',
    basePrice: 18.50,
    imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Michoacán, Mexico',
    inStock: true,
    featured: true,
  },
  {
    id: 'prod-003',
    sku: 'FP-SPI-03',
    name: 'Washed Baby Spinach Leaves',
    category: 'fresh_produce',
    subcategory: 'salad',
    categoryLabel: 'Fresh Produce',
    description: 'Triple-washed young tender spinach leaves. Ready for service, zero prep required.',
    packSize: '1kg Bag',
    unit: 'bag',
    basePrice: 4.90,
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=600&auto=format&fit=crop&q=80',
    moq: 2,
    origin: 'Evesham, Worcestershire, UK',
    inStock: true,
  },
  {
    id: 'prod-004',
    sku: 'FP-MUSH-04',
    name: 'Chef’s Wild Forest Mushroom Mix',
    category: 'fresh_produce',
    subcategory: 'vegetables',
    categoryLabel: 'Fresh Produce',
    description: 'Seasonal selection of Girolles, Pied de Mouton, Trompettes, and King Oyster mushrooms.',
    packSize: '1kg Basket',
    unit: 'kg',
    basePrice: 22.00,
    imageUrl: 'https://images.unsplash.com/photo-1509358271058-acd22cc93898?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Dordogne, France',
    inStock: true,
    featured: true,
  },
  {
    id: 'prod-005',
    sku: 'FP-LEM-05',
    name: 'Amalfi Coast PGI Lemons (Unwaxed)',
    category: 'fresh_produce',
    subcategory: 'citrus',
    categoryLabel: 'Fresh Produce',
    description: 'Aromatic, intensely fragrant untreated rind and sweet juice. Prized for cocktails and seafood.',
    packSize: '5kg Crate',
    unit: 'crate',
    basePrice: 16.50,
    imageUrl: 'https://images.unsplash.com/photo-1534939561126-855b8675edd7?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Sorrento, Italy',
    inStock: true,
  },
  {
    id: 'prod-006',
    sku: 'FP-POT-06',
    name: 'Selected Maris Piper Washed Potatoes',
    category: 'fresh_produce',
    subcategory: 'potatoes_onions',
    categoryLabel: 'Fresh Produce',
    description: 'Consistent dry matter for perfect hand-cut chips, mash, and golden roast potatoes.',
    packSize: '25kg Sack',
    unit: 'sack',
    basePrice: 14.20,
    imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=600&auto=format&fit=crop&q=80',
    moq: 2,
    origin: 'Lincolnshire, UK',
    inStock: true,
  },
  {
    id: 'prod-007',
    sku: 'FP-HERB-07',
    name: 'Live Micro Coriander & Pea Shoots Punnet Mix',
    category: 'fresh_produce',
    subcategory: 'herbs',
    categoryLabel: 'Fresh Produce',
    description: 'Living microgreens with root sponge. Exceptional shelf-life and vibrant chef garnish.',
    packSize: '8 Punnet Case',
    unit: 'case',
    basePrice: 12.80,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Warwickshire, UK',
    inStock: true,
  },

  // Foodservice - Dairy, Meats & Dry Goods
  {
    id: 'prod-008',
    sku: 'FS-CRM-08',
    name: 'Cotswold Dairy Pasteurized Double Cream',
    category: 'dairy_eggs',
    subcategory: 'dairy',
    categoryLabel: 'Dairy & Eggs',
    description: '48% butterfat content from grass-fed West Country cows. Whips beautifully without splitting.',
    packSize: '2 Litre Bottle',
    unit: 'bottle',
    basePrice: 7.90,
    imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=600&auto=format&fit=crop&q=80',
    moq: 2,
    origin: 'Gloucestershire, UK',
    allergens: ['Milk'],
    inStock: true,
  },
  {
    id: 'prod-009',
    sku: 'FS-EGG-09',
    name: 'British Lion Free Range Large Eggs',
    category: 'dairy_eggs',
    subcategory: 'eggs',
    categoryLabel: 'Dairy & Eggs',
    description: 'Class A large eggs with rich golden yolks. Graded and packed within 24 hours of lay.',
    packSize: '15 Dozen (180 Eggs)',
    unit: 'outer',
    basePrice: 34.50,
    imageUrl: 'https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Staffordshire, UK',
    allergens: ['Eggs'],
    inStock: true,
    featured: true,
  },
  {
    id: 'prod-010',
    sku: 'FS-BEEF-10',
    name: '28-Day Dry-Aged British Ribeye Steaks (250g)',
    category: 'meat_poultry',
    subcategory: 'beef_lamb',
    categoryLabel: 'Meat & Poultry',
    description: 'Himalayan salt chamber aged prime Hereford beef. Exceptional marbling and depth of flavour.',
    packSize: 'Pack of 10 (2.5kg)',
    unit: 'pack',
    basePrice: 78.00,
    imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Herefordshire, UK',
    inStock: true,
    featured: true,
  },
  {
    id: 'prod-011',
    sku: 'FS-TRUF-11',
    name: 'Italian White Truffle Infused EVOO',
    category: 'specialty',
    subcategory: 'truffles_caviar',
    categoryLabel: 'Specialty & Delicatessen',
    description: 'Cold-pressed extra virgin olive oil infused with real Tuber Magnatum Pico white truffle aroma.',
    packSize: '500ml Glass Bottle',
    unit: 'bottle',
    basePrice: 19.50,
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Piedmont, Italy',
    inStock: true,
  },
  {
    id: 'prod-012',
    sku: 'FS-CHOC-12',
    name: 'Valrhona Guanaja 70% Dark Chocolate Feves',
    category: 'dry_goods',
    subcategory: 'chocolate_pastry',
    categoryLabel: 'Pastry & Dry Goods',
    description: 'Iconic Grand Cru blend of Criollo and Trinitario beans. Benchmark pastry chocolate.',
    packSize: '3kg Bag',
    unit: 'bag',
    basePrice: 42.00,
    imageUrl: 'https://images.unsplash.com/photo-1549007994-cb92caebd54b?w=600&auto=format&fit=crop&q=80',
    moq: 1,
    origin: 'Tain-l’Hermitage, France',
    allergens: ['Soybeans', 'May contain Milk/Nuts'],
    inStock: true,
  },
];

export const INITIAL_ORGANIZATIONS: CustomerOrganization[] = [
  {
    id: 'org-sancarlo',
    name: 'San Carlo Ristorante Group',
    companyRegNumber: '08492019',
    vatNumber: 'GB 928 4810 22',
    sector: 'fine_dining',
    creditTier: 'premium',
    creditLimit: 15000,
    creditUsed: 3420.50,
    paymentTerms: '30 Days EOM',
    assignedSalesRep: 'Marcus Vance (Senior Key Account Manager)',
    assignedDepot: 'Birmingham Central Hub (B5 5JR)',
    discountTierPercent: 7.5,
    priceOverrides: {
      'prod-001': 7.80, // San Marzano Tomatoes base £9.80 -> £7.80
      'prod-010': 69.50, // Dry aged Ribeye base £78.00 -> £69.50
      'prod-005': 13.90, // Amalfi Lemons base £16.50 -> £13.90
    },
    lastOrderDate: '2026-08-14',
    status: 'active',
    locations: [
      {
        id: 'loc-sc-bham',
        name: 'San Carlo — Temple Street, Birmingham',
        addressLine1: '4 Temple Street',
        city: 'Birmingham',
        postcode: 'B2 5BN',
        deliveryInstructions: 'Kitchen entrance via rear service lane off Needlers Alley. 06:00 - 08:00 AM delivery window.',
        isPrimary: true,
      },
      {
        id: 'loc-sc-solihull',
        name: 'San Carlo — High Street, Solihull',
        addressLine1: '32 High Street',
        city: 'Solihull',
        postcode: 'B91 3TB',
        deliveryInstructions: 'Deliver to goods inwards door next to cellar ramp.',
        isPrimary: false,
      },
    ],
  },
  {
    id: 'org-grandhotel',
    name: 'The Grand Hotel Birmingham',
    companyRegNumber: '11928374',
    vatNumber: 'GB 381 9284 10',
    sector: 'boutique_hotel',
    creditTier: 'concierge',
    creditLimit: 30000,
    creditUsed: 8940.00,
    paymentTerms: '30 Days Net',
    assignedSalesRep: 'Marcus Vance (Senior Key Account Manager)',
    assignedDepot: 'Birmingham Central Hub (B5 5JR)',
    discountTierPercent: 10,
    priceOverrides: {
      'prod-008': 6.20, // Double cream base £7.90 -> £6.20
      'prod-009': 28.50, // Free range eggs base £34.50 -> £28.50
      'prod-002': 15.00, // Hass Avocado base £18.50 -> £15.00
    },
    lastOrderDate: '2026-08-16',
    status: 'active',
    locations: [
      {
        id: 'loc-gh-colmore',
        name: 'The Grand Hotel — Main Banqueting Kitchen',
        addressLine1: 'Church Street Loading Bay',
        city: 'Birmingham',
        postcode: 'B3 2FE',
        deliveryInstructions: 'Security barrier ring intercom 4. Forklift ramp access.',
        isPrimary: true,
      },
    ],
  },
  {
    id: 'org-opalcare',
    name: 'Opal Senior Care Living',
    companyRegNumber: '07182930',
    vatNumber: 'GB 192 8374 88',
    sector: 'other',
    creditTier: 'standard',
    creditLimit: 6000,
    creditUsed: 1200.00,
    paymentTerms: '14 Days Net',
    assignedSalesRep: 'Sarah Jenkins (Midlands Commercial Rep)',
    assignedDepot: 'Birmingham Central Hub (B5 5JR)',
    discountTierPercent: 5,
    priceOverrides: {
      'prod-006': 11.50, // Maris Piper potatoes £14.20 -> £11.50
      'prod-003': 3.90, // Baby spinach £4.90 -> £3.90
    },
    lastOrderDate: '2026-08-08', // Over 7 days ago - triggers inactive alert!
    status: 'active',
    locations: [
      {
        id: 'loc-opal-edgbaston',
        name: 'Opal Lodge — Edgbaston',
        addressLine1: '14 Harborne Road',
        city: 'Birmingham',
        postcode: 'B15 3AA',
        deliveryInstructions: 'Kitchen entrance at the rear garden access gate. Ring kitchen buzzer.',
        isPrimary: true,
      },
    ],
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-101',
    companyName: 'Simpsons Michelin Restaurant',
    contactName: 'Chef Luke Tipping',
    email: 'luke@simpsonsrestaurant.co.uk',
    phone: '0121 454 3434',
    sector: 'fine_dining',
    postcode: 'B15 3DZ',
    city: 'Birmingham',
    estimatedWeeklySpend: 4500,
    source: 'quote_request',
    status: 'quote_sent',
    assignedSalesRep: 'Marcus Vance',
    notes: 'Interested in bespoke heritage vegetable supply, micro-herbs, and French dairy lines. Quote sent with tier A pricing.',
    createdAt: '2026-08-12T10:30:00Z',
    requestedProducts: ['Wild Mushrooms', 'Heritage Tomatoes', 'Valrhona Chocolate'],
  },
  {
    id: 'lead-102',
    companyName: 'Edgbaston Boutique Hotel & Suites',
    contactName: 'Claire Davenport',
    email: 'c.davenport@edgbastonboutique.com',
    phone: '0121 454 5200',
    sector: 'boutique_hotel',
    postcode: 'B15 3EZ',
    city: 'Birmingham',
    estimatedWeeklySpend: 3200,
    source: 'website_form',
    status: 'price_list_sent',
    assignedSalesRep: 'Sarah Jenkins',
    notes: 'Looking to switch from national broadliner due to late morning deliveries. Needs 06:30 AM guaranteed arrival.',
    createdAt: '2026-08-14T14:15:00Z',
    requestedProducts: ['Free Range Eggs', 'Double Cream', 'Citrus & Avocados'],
  },
  {
    id: 'lead-103',
    companyName: 'Peel’s at Hampton Manor',
    contactName: 'David Taylor (Head of Purchasing)',
    email: 'purchasing@hamptonmanor.com',
    phone: '01675 446 080',
    sector: 'luxury_catering',
    postcode: 'B92 0EN',
    city: 'Solihull',
    estimatedWeeklySpend: 6000,
    source: 'referral',
    status: 'new_lead',
    assignedSalesRep: 'Marcus Vance',
    notes: 'New inquiry from referral. Estate dining & wedding banqueting. Requested immediate sales call regarding farm provenance.',
    createdAt: '2026-08-16T09:00:00Z',
  },
  {
    id: 'lead-104',
    companyName: 'Botanical Artisan Café & Bakery',
    contactName: 'Emma Walsh',
    email: 'emma@botanicalcafe.co.uk',
    phone: '0121 236 7890',
    sector: 'artisan_cafe',
    postcode: 'B3 1RB',
    city: 'Birmingham',
    estimatedWeeklySpend: 1400,
    source: 'google_search',
    status: 'contacted',
    assignedSalesRep: 'Sarah Jenkins',
    notes: 'Speciality sourdough baker and brunch kitchen. Needs daily organic milk, avocados, and fresh berries.',
    createdAt: '2026-08-15T16:20:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-10291',
    orderNumber: 'RW-10291',
    organizationId: 'org-sancarlo',
    organizationName: 'San Carlo Ristorante Group',
    locationName: 'San Carlo — Temple Street, Birmingham',
    status: 'out_for_delivery',
    deliveryDate: '2026-08-17',
    deliverySlot: 'Early Morning 05:30 - 07:30',
    deliveryNotes: 'Leave in walk-in cold room 1 if chef not present.',
    subtotal: 412.50,
    vatTotal: 15.60,
    total: 428.10,
    isStandingOrder: false,
    createdAt: '2026-08-16T22:15:00Z',
    updatedAt: '2026-08-17T05:10:00Z',
    items: [
      {
        productId: 'prod-001',
        sku: 'FP-TOM-01',
        name: 'San Marzano Vine Tomatoes',
        packSize: '6kg Box',
        qty: 6,
        unitPrice: 7.80,
        totalPrice: 46.80,
      },
      {
        productId: 'prod-002',
        sku: 'FP-AVO-02',
        name: 'Ready-to-Eat Hass Avocados (Size 16)',
        packSize: '16 Count Box',
        qty: 4,
        unitPrice: 17.11,
        totalPrice: 68.44,
      },
      {
        productId: 'prod-010',
        sku: 'FS-BEEF-10',
        name: '28-Day Dry-Aged British Ribeye Steaks (250g)',
        packSize: 'Pack of 10 (2.5kg)',
        qty: 4,
        unitPrice: 69.50,
        totalPrice: 278.00,
      },
      {
        productId: 'prod-005',
        sku: 'FP-LEM-05',
        name: 'Amalfi Coast PGI Lemons (Unwaxed)',
        packSize: '5kg Crate',
        qty: 2,
        unitPrice: 13.90,
        totalPrice: 27.80,
      },
    ],
    trackingHistory: [
      { status: 'received', timestamp: '2026-08-16 22:15', note: 'Order placed by Head Chef Marco' },
      { status: 'confirmed', timestamp: '2026-08-16 22:20', note: 'Order confirmed & inventory allocated' },
      { status: 'picking', timestamp: '2026-08-17 03:30', note: 'Picking list dispatched at Birmingham Hub' },
      { status: 'dispatch_ready', timestamp: '2026-08-17 04:45', note: 'Checked & loaded onto Van 04' },
      { status: 'out_for_delivery', timestamp: '2026-08-17 05:15', note: 'Driver David en route to Temple Street (Est: 06:20 AM)' },
    ],
  },
  {
    id: 'ord-10284',
    orderNumber: 'RW-10284',
    organizationId: 'org-sancarlo',
    organizationName: 'San Carlo Ristorante Group',
    locationName: 'San Carlo — Temple Street, Birmingham',
    status: 'delivered',
    deliveryDate: '2026-08-14',
    deliverySlot: 'Early Morning 05:30 - 07:30',
    subtotal: 512.40,
    vatTotal: 22.10,
    total: 534.50,
    isStandingOrder: true,
    recurrence: 'weekly',
    createdAt: '2026-08-13T21:40:00Z',
    updatedAt: '2026-08-14T06:45:00Z',
    items: [
      {
        productId: 'prod-001',
        sku: 'FP-TOM-01',
        name: 'San Marzano Vine Tomatoes',
        packSize: '6kg Box',
        qty: 8,
        unitPrice: 7.80,
        totalPrice: 62.40,
      },
      {
        productId: 'prod-004',
        sku: 'FP-MUSH-04',
        name: 'Chef’s Wild Forest Mushroom Mix',
        packSize: '1kg Basket',
        qty: 5,
        unitPrice: 20.35,
        totalPrice: 101.75,
      },
      {
        productId: 'prod-006',
        sku: 'FP-POT-06',
        name: 'Selected Maris Piper Washed Potatoes',
        packSize: '25kg Sack',
        qty: 6,
        unitPrice: 13.14,
        totalPrice: 78.84,
      },
      {
        productId: 'prod-010',
        sku: 'FS-BEEF-10',
        name: '28-Day Dry-Aged British Ribeye Steaks (250g)',
        packSize: 'Pack of 10 (2.5kg)',
        qty: 4,
        unitPrice: 69.50,
        totalPrice: 278.00,
      },
    ],
    trackingHistory: [
      { status: 'received', timestamp: '2026-08-13 21:40' },
      { status: 'confirmed', timestamp: '2026-08-13 21:45' },
      { status: 'picking', timestamp: '2026-08-14 03:15' },
      { status: 'dispatch_ready', timestamp: '2026-08-14 04:30' },
      { status: 'out_for_delivery', timestamp: '2026-08-14 05:20' },
      { status: 'delivered', timestamp: '2026-08-14 06:45', note: 'Signed for by Sous Chef Giovanni' },
    ],
  },
  {
    id: 'ord-10280',
    orderNumber: 'RW-10280',
    organizationId: 'org-grandhotel',
    organizationName: 'The Grand Hotel Birmingham',
    locationName: 'The Grand Hotel — Main Banqueting Kitchen',
    status: 'delivered',
    deliveryDate: '2026-08-16',
    deliverySlot: 'Morning 06:00 - 08:30',
    subtotal: 1240.00,
    vatTotal: 64.00,
    total: 1304.00,
    isStandingOrder: false,
    createdAt: '2026-08-15T19:00:00Z',
    updatedAt: '2026-08-16T07:15:00Z',
    items: [
      {
        productId: 'prod-008',
        sku: 'FS-CRM-08',
        name: 'Cotswold Dairy Pasteurized Double Cream',
        packSize: '2 Litre Bottle',
        qty: 24,
        unitPrice: 6.20,
        totalPrice: 148.80,
      },
      {
        productId: 'prod-009',
        sku: 'FS-EGG-09',
        name: 'British Lion Free Range Large Eggs',
        packSize: '15 Dozen (180 Eggs)',
        qty: 10,
        unitPrice: 28.50,
        totalPrice: 285.00,
      },
      {
        productId: 'prod-012',
        sku: 'FS-CHOC-12',
        name: 'Valrhona Guanaja 70% Dark Chocolate Feves',
        packSize: '3kg Bag',
        qty: 6,
        unitPrice: 37.80,
        totalPrice: 226.80,
      },
      {
        productId: 'prod-002',
        sku: 'FP-AVO-02',
        name: 'Ready-to-Eat Hass Avocados (Size 16)',
        packSize: '16 Count Box',
        qty: 12,
        unitPrice: 15.00,
        totalPrice: 180.00,
      },
    ],
    trackingHistory: [
      { status: 'delivered', timestamp: '2026-08-16 07:15', note: 'Received at Church St Loading bay' },
    ],
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-8921',
    invoiceNumber: 'INV-2026-8921',
    orderId: 'ord-10284',
    orderNumber: 'RW-10284',
    organizationId: 'org-sancarlo',
    issueDate: '2026-08-14',
    dueDate: '2026-09-30',
    subtotal: 512.40,
    vatAmount: 22.10,
    totalAmount: 534.50,
    status: 'open',
  },
  {
    id: 'inv-8840',
    invoiceNumber: 'INV-2026-8840',
    orderNumber: 'RW-10240',
    organizationId: 'org-sancarlo',
    issueDate: '2026-08-07',
    dueDate: '2026-09-30',
    subtotal: 840.00,
    vatAmount: 38.50,
    totalAmount: 878.50,
    status: 'open',
  },
  {
    id: 'inv-8712',
    invoiceNumber: 'INV-2026-8712',
    orderNumber: 'RW-10190',
    organizationId: 'org-sancarlo',
    issueDate: '2026-07-31',
    dueDate: '2026-08-31',
    subtotal: 1940.00,
    vatAmount: 67.50,
    totalAmount: 2007.50,
    status: 'paid',
  },
  {
    id: 'inv-8902',
    invoiceNumber: 'INV-2026-8902',
    orderId: 'ord-10280',
    orderNumber: 'RW-10280',
    organizationId: 'org-grandhotel',
    issueDate: '2026-08-16',
    dueDate: '2026-09-15',
    subtotal: 1240.00,
    vatAmount: 64.00,
    totalAmount: 1304.00,
    status: 'open',
  },
];
